routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::resource('departement', 'DepartementController');
Route::resource('prof', 'ProfController');
Route::resource('responsable', 'ResponsableController');
Route::resource('coordinateur', 'CoordinateurController');
Route::resource('filiere', 'FiliereController');


Route::get('/site', 'SiteController@index');
Route::get('/site/departs', 'SiteController@departs');
Route::get('/site/filieres', 'SiteController@filieres');
Route::get('/site/cycleprepa', 'SiteController@cycleprepa');
Route::get('/site/formations', 'SiteController@formations');
Route::get('/site/gallery', 'SiteController@gallery');

Route::get('/site/offre', 'SiteController@offre');

Route::get('/site/filieres/1', 'SiteController@ginfo');
Route::get('/site/filieres/3', 'SiteController@gindus');
Route::get('/site/filieres/2', 'SiteController@gtr');
Route::get('/site/filieres/4', 'SiteController@gpmc');

Route::get('/site/bde', 'SiteController@bde');
Route::get('/site/clubs', 'SiteController@clubs');
Route::get('/site/reglement', 'SiteController@reglement');

Route::get('/site/news', 'SiteController@news');
Route::get('/site/emploi', 'SiteController@emploi');

app/Departement.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Departement extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'titre', 'image'
    ];

    public function profs(){
    	return $this->hasMany(Prof::class, 'departement_id');
    }

    public function coordinateurs(){
    	return $this->hasMany(Coordinateur::class, 'departement_id');
    }

    public function responsables(){
    	return $this->hasMany(Responsable::class, 'departement_id');
    }

    public function filieres(){
        return $this->hasMany(Filiere::class, 'departement_id');
    }

    public function formations(){
        return $this->belongsToMany(Formation::class);
    }
}

app/Http/Controllers/DepartementController.php
<?php

namespace App\Http\Controllers;

use App\Departement;
use Illuminate\Http\Request;
use App\Http\Requests\DepartementRequest;

class DepartementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departements=Departement::paginate(2);
        return view('departements.index', compact('departements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departements.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $image = $request->get('titre').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('departements/images'), $image);
        $departement=new Departement(
            [
                'titre'=>$request->get('titre'),
                'image'=>$request->get('image')
            ]
        );
        $departement->save();
        return redirect('/departement')->with('success', 'Departement has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Departement  $departement
     * @return \Illuminate\Http\Response
     */
    public function show(Departement $departement)
    {
        return view('departements.show', compact('departement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Departement  $departement
     * @return \Illuminate\Http\Response
     */
    public function edit(Departement $departement)
    {
        return view('departements.edit', compact('departement'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Departement  $departement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Departement $departement)
    {
        
        $image = $request->get('titre').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('departements/images'), $image);  
        $departement->titre=$request->get('titre');  
        $departement->image=$image; 
        $departement->save();
        return redirect('/departement')->with('success', 'Departement has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Departement  $departement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Departement $departement)
    {
        $departement->delete();
        return redirect('/departement')->with('success', 'Departement has been removed');
    }
}

resources/views/departements/create.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.index')}}">Departements</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.create')}}">New Departement</a>
    </li>
  </ul>
<div class="card uper">
  <div class="card-header">
    Ajouter departement
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('departement.store') }}" enctype="multipart/form-data">
          @csrf
          <div class="form-group">
              <label for="titre">Titre:</label>
              <input type="text" class="form-control" name="titre"/>
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <input type="file" class="form-control" name="image"/>
          </div>
          <button type="submit" class="btn btn-primary">Ajouter</button>
      </form>
  </div>
</div>
@endsection

resources/views/departements/edit.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.index')}}">Departements</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.create')}}">New Departement</a>
    </li>
  </ul>
<div class="card uper">
  <div class="card-header">
    Modifier departement
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('departement.update', $departement->id) }}" enctype="multipart/form-data">
          @method('PATCH')
          @csrf
          <div class="form-group">
              <label for="titre">Titre:</label>
              <input type="text" class="form-control" name="titre" value="{{$departement->titre}}" />
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <label><img src="{{ url('/') }}/departements/images/{{$departement->image}}" height="40" width="60" alt="No Image" /></label>
              <input type="file" class="form-control" name="image"/>
          </div>
          <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
  </div>
</div>
@endsection

resources/views/departements/index.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.index')}}">Departements</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.create')}}">New Departement</a>
    </li>
  </ul>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Titre</td>
          <td>Image</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($departements as $departement)
        <tr>
            <td>{{$departement->id}}</td>
            <td>{{$departement->titre}}</td>
            <td><img src="{{ url('/') }}/departements/images/{{$departement->image}}" height="40" width="60" alt="No Image"></td>
            <td><a href="{{ route('departement.show',$departement->id)}}" class="btn btn-primary">Show</a></td>
            <td><a href="{{ route('departement.edit',$departement->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form class="delete" action="{{ route('departement.destroy', $departement->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $departements->links() }}
<div>
@endsection

resources/views/departements/show.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.index')}}">Departements</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.create')}}">New Departement</a>
    </li>
  </ul>
<div class="card uper">
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Titre</td>
          <td>Image</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{$departement->id}}</td>
            <td>{{$departement->titre}}</td>
            <td><img src="{{ url('/') }}/departements/images/{{$departement->image}}" height="40" width="60" alt="No Image"></td>
            <td><a href="{{ route('departement.edit',$departement->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('departement.destroy', $departement->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
    </tbody>
</div>
@endsection