routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::resource('departement', 'DepartementController');
Route::resource('prof', 'ProfController');
Route::resource('responsable', 'ResponsableController');
Route::resource('coordinateur', 'CoordinateurController');
Route::resource('filiere', 'FiliereController');


Route::get('/site', 'SiteController@index');
Route::get('/site/departs', 'SiteController@departs');
Route::get('/site/filieres', 'SiteController@filieres');
Route::get('/site/cycleprepa', 'SiteController@cycleprepa');
Route::get('/site/formations', 'SiteController@formations');
Route::get('/site/gallery', 'SiteController@gallery');

Route::get('/site/offre', 'SiteController@offre');

Route::get('/site/filieres/1', 'SiteController@ginfo');
Route::get('/site/filieres/3', 'SiteController@gindus');
Route::get('/site/filieres/2', 'SiteController@gtr');
Route::get('/site/filieres/4', 'SiteController@gpmc');

Route::get('/site/bde', 'SiteController@bde');
Route::get('/site/clubs', 'SiteController@clubs');
Route::get('/site/reglement', 'SiteController@reglement');

Route::get('/site/news', 'SiteController@news');
Route::get('/site/emploi', 'SiteController@emploi');

app/Coordinateur.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Coordinateur extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nom', 'prenom', 'image', 'description'
    ];

    public function departement(){
    	return $this->belongsTo(Departement::class, 'departement_id');
    }

    public function filiere(){
        return $this->hasOne(Filiere::class);
    }
}

app/Http/Controllers/CoordinateurController.php
<?php

namespace App\Http\Controllers;

use App\Coordinateur;
use App\Departement;
use Illuminate\Http\Request;
use App\Http\Requests\CoordinateurRequest;

class CoordinateurController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coordinateurs=Coordinateur::paginate(2);
        return view('coordinateurs.index', compact('coordinateurs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departements=Departement::all();
        return view('coordinateurs.create', compact('departements'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CoordinateurRequest $request)
    {
        $image = $request->get('nom').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('coordinateurs/images'), $image);
        $departement=Departement::find($request->get('departement_id'));
        $coordinateur=new Coordinateur(
            [
                'nom'=>$request->get('nom'),
                'prenom'=>$request->get('prenom'),
                'description'=>$request->get('description'),
                'image'=>$image,
            ]
        );
        $coordinateur->departement()->associate($departement);
        $coordinateur->save();
        return redirect('/coordinateur')->with('success', 'Coordinateur has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Coordinateur  $coordinateur
     * @return \Illuminate\Http\Response
     */
    public function show(Coordinateur $coordinateur)
    {
        return view('coordinateurs.show', compact('coordinateur'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Coordinateur  $coordinateur
     * @return \Illuminate\Http\Response
     */
    public function edit(Coordinateur $coordinateur)
    {
        $departements=Departement::all();
        return view('coordinateurs.edit', compact(['coordinateur', 'departements']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Coordinateur  $coordinateur
     * @return \Illuminate\Http\Response
     */
    public function update(CoordinateurRequest $request, Coordinateur $coordinateur)
    {
        $image = $request->get('nom').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('coordinateurs/images'), $image);
        $departement=Departement::find($request->get('departement_id'));
        $coordinateur->nom=$request->get('nom');
        $coordinateur->prenom=$request->get('prenom');
        $coordinateur->description=$request->get('description');
        $coordinateur->image=$image;
        $coordinateur->departement()->associate($departement);
        $coordinateur->save();
        return redirect('/coordinateur')->with('success', 'Coordinateur has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Coordinateur  $coordinateur
     * @return \Illuminate\Http\Response
     */
    public function destroy(Coordinateur $coordinateur)
    {
        $coordinateur->delete();
        return redirect('/coordinateur')->with('success', 'Coordinateur has been removed');
    }
}

resources/views/coordinateurs/create.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.index')}}">Coordinateurs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.create')}}">New Coordinateur</a>
    </li>
</ul>
<div class="card uper">
  <div class="card-header">
    Ajouter coordinateur
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('coordinateur.store') }}" enctype="multipart/form-data">
              @csrf
          <div class="form-group">
              <label for="nom">Nom:</label>
              <input type="text" class="form-control" name="nom"/>
          </div>
          <div class="form-group">
              <label for="prenom">Prenom:</label>
              <input type="text" class="form-control" name="prenom"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <input type="file" class="form-control" name="image"/>
          </div>
          <div class="form-group">
              <label for="departement_id">Deparetement:</label>
              <select class="form-control" name="departement_id">
                @foreach ($departements as $departement)
                  <option value="{{$departement->id}}">{{ $departement->titre }}</option>
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Ajouter</button>
      </form>
  </div>
</div>
@endsection

resources/views/coordinateurs/edit.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.index')}}">Coordinateurs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.create')}}">New Coordinateur</a>
    </li>
</ul>
<div class="card uper">
  <div class="card-header">
    Ajouter coordinateur
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('coordinateur.update', $coordinateur->id) }}" enctype="multipart/form-data">
          @csrf
          @method('PATCH')
          <div class="form-group">
              <label for="nom">Nom:</label>
              <input type="text" class="form-control" name="nom" value="{{$coordinateur->nom}}" />
          </div>
          <div class="form-group">
              <label for="prenom">Prenom:</label>
              <input type="text" class="form-control" name="prenom" value="{{$coordinateur->prenom}}"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description" value="{{$coordinateur->description}}"/>
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <td><img src="{{ url('/') }}/coordinateurs/images/{{$coordinateur->image}}" height="40" width="60" alt="No Image"></td>
              <input type="file" class="form-control" name="image"/>
          </div>
          <div class="form-group">
              <label for="departement_id">Deparetement:</label>
              <select class="form-control" name="departement_id">
                @foreach ($departements as $departement)
                  @if($coordinateur->departement->titre==$departement->titre)
                    <option value="{{$departement->id}}" selected>{{ $departement->titre }}</option>
                  @else
                    <option value="{{$departement->id}}">{{ $departement->titre }}</option>
                  @endif
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
  </div>
</div>
@endsection

resources/views/coordinateurs/index.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.index')}}">Coordinateurs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.create')}}">New Coordinateur</a>
    </li>
</ul>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nom</td>
          <td>Prenom</td>
          <td>Description</td>
          <td>Image</td>
          <td>Departement</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($coordinateurs as $coordinateur)
        <tr>
            <td>{{$coordinateur->id}}</td>
            <td>{{$coordinateur->nom}}</td>
            <td>{{$coordinateur->prenom}}</td>
            <td>{{$coordinateur->description}}</td>
            <td><img src="{{ url('/') }}/coordinateurs/images/{{$coordinateur->image}}" height="40" width="60" alt="No Image"></td>
            <td>{{$coordinateur->departement->titre}}</td>
            <td><a href="{{ route('coordinateur.show',$coordinateur->id)}}" class="btn btn-primary">Show</a></td>
            <td><a href="{{ route('coordinateur.edit',$coordinateur->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form class="delete" action="{{ route('coordinateur.destroy', $coordinateur->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $coordinateurs->links() }}
<div>
@endsection

resources/views/coordinateurs/show.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.index')}}">Coordinateurs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('coordinateur.create')}}">New Coordinateur</a>
    </li>
</ul>
<div class="uper">
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nom</td>
          <td>Prenom</td>
          <td>Description</td>
          <td>Image</td>
          <td>Departement</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{$coordinateur->id}}</td>
            <td>{{$coordinateur->nom}}</td>
            <td>{{$coordinateur->prenom}}</td>
            <td>{{$coordinateur->description}}</td>
            <td><img src="{{ url('/') }}/coordinateurs/images/{{$coordinateur->image}}" height="40" width="60" alt="No Image"></td>
            <td>{{$coordinateur->departement->titre}}</td>
            <td><a href="{{ route('coordinateur.show',$coordinateur->id)}}" class="btn btn-primary">Show</a></td>
            <td><a href="{{ route('coordinateur.edit',$coordinateur->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form class="delete" action="{{ route('coordinateur.destroy', $coordinateur->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
    </tbody>
  </table>
<div>
@endsection