routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::resource('departement', 'DepartementController');
Route::resource('prof', 'ProfController');
Route::resource('responsable', 'ResponsableController');
Route::resource('coordinateur', 'CoordinateurController');
Route::resource('filiere', 'FiliereController');


Route::get('/site', 'SiteController@index');
Route::get('/site/departs', 'SiteController@departs');
Route::get('/site/filieres', 'SiteController@filieres');
Route::get('/site/cycleprepa', 'SiteController@cycleprepa');
Route::get('/site/formations', 'SiteController@formations');
Route::get('/site/gallery', 'SiteController@gallery');

Route::get('/site/offre', 'SiteController@offre');

Route::get('/site/filieres/1', 'SiteController@ginfo');
Route::get('/site/filieres/3', 'SiteController@gindus');
Route::get('/site/filieres/2', 'SiteController@gtr');
Route::get('/site/filieres/4', 'SiteController@gpmc');

Route::get('/site/bde', 'SiteController@bde');
Route::get('/site/clubs', 'SiteController@clubs');
Route::get('/site/reglement', 'SiteController@reglement');

Route::get('/site/news', 'SiteController@news');
Route::get('/site/emploi', 'SiteController@emploi');

app/Filiere.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Filiere extends Model
{
     use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'titre', 'image'
    ];

    public function departement(){
    	return $this->belongsTo(Departement::class, 'departement_id');
    }

    public function coordinateur(){
    	return $this->belongsTo(Coordinateur::class, 'coordinateur_id');
    }

    public function responsable(){
    	return $this->belongsTo(Responsable::class, 'responsable_id');
    }
    
    public function emploi(){
        return $this->hasOne(Emploi::class);
    }
}

app/Http/Controllers/FiliereController.php
<?php

namespace App\Http\Controllers;

use App\Filiere;
use App\Departement;
use App\Responsable;
use App\Coordinateur;
use Illuminate\Http\Request;
use App\Http\Requests\FiliereRequest;

class FiliereController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $filieres=Filiere::paginate(2);
        return view('filieres.index', compact('filieres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departements=Departement::all();
        $responsables=Responsable::all();
        $coordinateurs=Coordinateur::all();
        return view('filieres.create', compact(['departements', 'responsables', 'coordinateurs']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FiliereRequest $request)
    {
        $image = $request->get('titre').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('filieres/images'), $image);
        $departement=Departement::find($request->get('departement_id'));
        $responsable=Responsable::find($request->get('responsable_id'));
        $coordinateur=Coordinateur::find($request->get('coordinateur_id'));
        $filiere=new Filiere(
            [
                'titre'=>$request->get('titre'),
                'image'=>$image
            ]
        );
        $filiere->departement()->associate($departement);
        $responsable->filiere()->save($filiere);
        $coordinateur->filiere()->save($filiere);
        return redirect('/filiere')->with('success', 'Filiere has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Filiere  $filiere
     * @return \Illuminate\Http\Response
     */
    public function show(Filiere $filiere)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Filiere  $filiere
     * @return \Illuminate\Http\Response
     */
    public function edit(Filiere $filiere)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Filiere  $filiere
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Filiere $filiere)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Filiere  $filiere
     * @return \Illuminate\Http\Response
     */
    public function destroy(Filiere $filiere)
    {
        //
    }
}

resources/views/filieres/create.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('filiere.index')}}">Filieres</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('filiere.create')}}">New Filiere</a>
    </li>
</ul>
<div class="card uper">
  <div class="card-header">
    Ajouter Filiere
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('filiere.store') }}" enctype="multipart/form-data">
          @csrf
          <div class="form-group">
              <label for="titre">Titre:</label>
              <input type="text" class="form-control" name="titre"/>
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <input type="file" class="form-control" name="image"/>
          </div>
          <div class="form-group">
              <label for="departement_id">Deparetement:</label>
              <select class="form-control" name="departement_id">
                @foreach ($departements as $departement)
                  <option value="{{$departement->id}}">{{ $departement->titre }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="responsable_id">Responsable:</label>
              <select class="form-control" name="responsable_id">
                @foreach ($responsables as $responsable)
                  <option value="{{$responsable->id}}">{{ $responsable->nom }} {{ $responsable->prenom }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="coordinateur_id">Coordinateur:</label>
              <select class="form-control" name="coordinateur_id">
                @foreach ($coordinateurs as $coordinateur)
                  <option value="{{$coordinateur->id}}">{{ $coordinateur->nom }} {{ $coordinateur->prenom }}</option>
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Ajouter</button>
      </form>
  </div>
</div>
@endsection

resources/views/filieres/edit.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('filiere.index')}}">Filieres</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('filiere.create')}}">New Filiere</a>
    </li>
</ul>
<div class="card uper">
  <div class="card-header">
    Modifier Filiere
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('departement.update', $departement->id) }}" enctype="multipart/form-data">
          @method('PATCH')
          @csrf
          <div class="form-group">
              <label for="titre">Titre:</label>
              <input type="text" class="form-control" name="titre" value="{{$filiere->titre}}" />
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <td><img src="{{ url('/') }}/filieres/images/{{$filiere->image}}" height="40" width="60" alt="No Image"></td>
              <input type="file" class="form-control" name="image"/>
          </div>
          <div class="form-group">
              <label for="departement_id">Deparetement:</label>
              <select class="form-control" name="departement_id">
                @foreach ($departements as $departement)
                  @if($filiere->departement->titre==$departement->titre)
                    <option value="{{$departement->id}}" selected>{{ $departement->titre }}</option>
                  @else
                    <option value="{{$departement->id}}">{{ $departement->titre }}</option>
                  @endif
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="departement_id">Responsable:</label>
              <select class="form-control" name="departement_id">
                @foreach ($responsables as $responsable)
                  @if($filiere->responsable==$responsable)
                    <option value="{{$responsable->id}}" selected>{{ $responsable->nom $responsable->prenom }}</option>
                  @else
                    <option value="{{$responsable->id}}">{{ $responsable->nom $responsable->prenom }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="departement_id">Coordinateur:</label>
              <select class="form-control" name="departement_id">
                @foreach ($coordinateurs as $coordinateur)
                  @if($filiere->coordinateur==$coordinateur)
                    <option value="{{$coordinateur->id}}" selected>{{ $coordinateur->nom $coordinateur->prenom }}</option>
                  @else
                    <option value="{{$coordinateur->id}}">{{ $coordinateur->nom $coordinateur->prenom }}</option>
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
  </div>
</div>
@endsection

resources/views/filieres/index.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('filiere.index')}}">Filieres</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('filiere.create')}}">New Filiere</a>
    </li>
  </ul>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Titre</td>
          <td>Image</td>
          <td>Departement</td>
          <td>Responsable</td>
          <td>Coordinateur</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($filieres as $filiere)
        <tr>
            <td>{{$filiere->id}}</td>
            <td>{{$filiere->titre}}</td>
            <td><img src="{{ url('/') }}/filieres/images/{{$filiere->image}}" height="40" width="60" alt="No Image"></td>
            <td>{{$filiere->departement->titre}}</td>
            <td>{{$filiere->responsable->nom}} {{$filiere->responsable->prenom}}</td>
            <td>{{$filiere->coordinateur->nom}} {{$filiere->coordinateur->prenom}}</td>
            <td><a href="{{ route('filiere.show',$filiere->id)}}" class="btn btn-primary">Show</a></td>
            <td><a href="{{ route('filiere.edit',$filiere->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form class="delete" action="{{ route('filiere.destroy', $filiere->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $filieres->links() }}
<div>
@endsection

resources/views/filieres/show.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.index')}}">Departements</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('departement.create')}}">New Departement</a>
    </li>
  </ul>
<div class="card uper">
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Titre</td>
          <td>Image</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{$departement->id}}</td>
            <td>{{$departement->titre}}</td>
            <td><img src="{{ url('/') }}/departements/images/{{$departement->image}}" height="40" width="60" alt="No Image"></td>
            <td><a href="{{ route('departement.edit',$departement->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('departement.destroy', $departement->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
    </tbody>
</div>
@endsection