routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::resource('departement', 'DepartementController');
Route::resource('prof', 'ProfController');
Route::resource('responsable', 'ResponsableController');
Route::resource('coordinateur', 'CoordinateurController');
Route::resource('filiere', 'FiliereController');


Route::get('/site', 'SiteController@index');
Route::get('/site/departs', 'SiteController@departs');
Route::get('/site/filieres', 'SiteController@filieres');
Route::get('/site/cycleprepa', 'SiteController@cycleprepa');
Route::get('/site/formations', 'SiteController@formations');
Route::get('/site/gallery', 'SiteController@gallery');

Route::get('/site/offre', 'SiteController@offre');

Route::get('/site/filieres/1', 'SiteController@ginfo');
Route::get('/site/filieres/3', 'SiteController@gindus');
Route::get('/site/filieres/2', 'SiteController@gtr');
Route::get('/site/filieres/4', 'SiteController@gpmc');

Route::get('/site/bde', 'SiteController@bde');
Route::get('/site/clubs', 'SiteController@clubs');
Route::get('/site/reglement', 'SiteController@reglement');

Route::get('/site/news', 'SiteController@news');
Route::get('/site/emploi', 'SiteController@emploi');

app/Responsable.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Responsable extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nom', 'prenom', 'image', 'description'
    ];

    public function departement(){
    	return $this->belongsTo(Departement::class, 'departement_id');
    }

    public function filiere(){
        return $this->hasOne(Filiere::class);
    }
}

app/Http/Controllers/ResponsableController.php
<?php

namespace App\Http\Controllers;

use App\Responsable;
use App\Departement;
use Illuminate\Http\Request;
use App\Http\Requests\ResponsableRequest;

class ResponsableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $responsables=Responsable::paginate(2);
        return view('responsables.index', compact('responsables'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departements=Departement::all();
        return view('responsables.create', compact('departements'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ResponsableRequest $request)
    {
        $image = $request->get('nom').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('responsables/images'), $image);
        $departement=Departement::find($request->get('departement_id'));
        $responsable=new Responsable(
            [
                'nom'=>$request->get('nom'),
                'prenom'=>$request->get('prenom'),
                'description'=>$request->get('description'),
                'image'=>$image,
            ]
        );
        $responsable->departement()->associate($departement);
        $responsable->save();
        return redirect('/responsable')->with('success', 'Responsable has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Responsable  $responsable
     * @return \Illuminate\Http\Response
     */
    public function show(Responsable $responsable)
    {
        return view('responsables.show', compact('responsable'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Responsable  $responsable
     * @return \Illuminate\Http\Response
     */
    public function edit(Responsable $responsable)
    {
        $departements=Departement::all();
        return view('responsables.edit', compact(['responsable', 'departements']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Responsable  $responsable
     * @return \Illuminate\Http\Response
     */
    public function update(ResponsableRequest $request, Responsable $responsable)
    {
        $image = $request->get('nom').''.time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('responsables/images'), $image);
        $departement=Departement::find($request->get('departement_id'));
        $responsable->nom=$request->get('nom');
        $responsable->prenom=$request->get('prenom');
        $responsable->description=$request->get('description');
        $responsable->image=$image;
        $responsable->departement()->associate($departement);
        $responsable->save();
        return redirect('/responsable')->with('success', 'Responsable has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Responsable  $responsable
     * @return \Illuminate\Http\Response
     */
    public function destroy(Responsable $responsable)
    {
        $responsable->delete();
        return redirect('/responsable')->with('success', 'Responsable has been removed');
    }
}

resources/views/responsables/create.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.index')}}">Responsables</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.create')}}">New Responsable</a>
    </li>
</ul>
<div class="card uper">
  <div class="card-header">
    Ajouter Responsable
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('responsable.store') }}" enctype="multipart/form-data">
              @csrf
          <div class="form-group">
              <label for="nom">Nom:</label>
              <input type="text" class="form-control" name="nom"/>
          </div>
          <div class="form-group">
              <label for="prenom">Prenom:</label>
              <input type="text" class="form-control" name="prenom"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <input type="file" class="form-control" name="image"/>
          </div>
          <div class="form-group">
              <label for="departement_id">Deparetement:</label>
              <select class="form-control" name="departement_id">
                @foreach ($departements as $departement)
                  <option value="{{$departement->id}}">{{ $departement->titre }}</option>
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Ajouter</button>
      </form>
  </div>
</div>
@endsection

resources/views/responsables/edit.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.index')}}">Responsables</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.create')}}">New Responsable</a>
    </li>
</ul>
<div class="card uper">
  <div class="card-header">
    Ajouter Responsable
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('responsable.update', $responsable->id) }}" enctype="multipart/form-data">
          @csrf
          @method('PATCH')
          <div class="form-group">
              <label for="nom">Nom:</label>
              <input type="text" class="form-control" name="nom" value="{{$responsable->nom}}" />
          </div>
          <div class="form-group">
              <label for="prenom">Prenom:</label>
              <input type="text" class="form-control" name="prenom" value="{{$responsable->prenom}}"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description" value="{{$responsable->description}}"/>
          </div>
          <div class="form-group">
              <label for="image">Image:</label>
              <td><img src="{{ url('/') }}/responsables/images/{{$responsable->image}}" height="40" width="60" alt="No Image"></td>
              <input type="file" class="form-control" name="image"/>
          </div>
          <div class="form-group">
              <label for="departement_id">Deparetement:</label>
              <select class="form-control" name="departement_id">
                @foreach ($departements as $departement)
                  @if($responsable->departement->titre==$departement->titre)
                    <option value="{{$departement->id}}" selected>{{ $departement->titre }}</option>
                  @else
                    <option value="{{$departement->id}}">{{ $departement->titre }}</option>
                  @endif
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
  </div>
</div>
@endsection

resources/views/responsables/index.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.index')}}">Responsables</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.create')}}">New Responsable</a>
    </li>
</ul>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nom</td>
          <td>Prenom</td>
          <td>Description</td>
          <td>Image</td>
          <td>Departement</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($responsables as $responsable)
        <tr>
            <td>{{$responsable->id}}</td>
            <td>{{$responsable->nom}}</td>
            <td>{{$responsable->prenom}}</td>
            <td>{{$responsable->description}}</td>
            <td><img src="{{ url('/') }}/responsables/images/{{$responsable->image}}" height="40" width="60" alt="No Image"></td>
            <td>{{$responsable->departement->titre}}</td>
            <td><a href="{{ route('responsable.show',$responsable->id)}}" class="btn btn-primary">Show</a></td>
            <td><a href="{{ route('responsable.edit',$responsable->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form class="delete" action="{{ route('responsable.destroy', $responsable->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $responsables->links() }}
<div>
@endsection

resources/views/responsables/show.blade.php
@extends('layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.index')}}">Responsables</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ route('responsable.create')}}">New Responsable</a>
    </li>
</ul>
<div class="uper">
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nom</td>
          <td>Prenom</td>
          <td>Description</td>
          <td>Image</td>
          <td>Departement</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{$responsable->id}}</td>
            <td>{{$responsable->nom}}</td>
            <td>{{$responsable->prenom}}</td>
            <td>{{$responsable->description}}</td>
            <td><img src="{{ url('/') }}/responsables/images/{{$responsable->image}}" height="40" width="60" alt="No Image"></td>
            <td>{{$responsable->departement->titre}}</td>
            <td><a href="{{ route('responsable.show',$responsable->id)}}" class="btn btn-primary">Show</a></td>
            <td><a href="{{ route('responsable.edit',$responsable->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form class="delete" action="{{ route('responsable.destroy', $responsable->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
    </tbody>
  </table>
<div>
@endsection